resolver: lts-13.20
packages:
- .
- ghc-events
- ghc-events-sqlite
- gtk-demo
extra-deps:
- cairo-0.13.6.0
- gio-0.13.6.0
- glib-0.13.7.0
- gtk-0.15.2
- gtk2hs-buildtools-0.13.5.0
- pango-0.13.6.0
flags: {}

build:
    library-profiling: true
    executable-profiling: false
    haddock: false